dist: trusty
sudo: true
language: scala
scala:
  - 2.12.8
jdk:
  - oraclejdk8

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - e.shredinger@yahoo.com
    on_success: change
    on_failure: always


script:
  - sbt ++$TRAVIS_SCALA_VERSION clean coverage test coverageReport

after_success:
  - bash <(curl -s https://codecov.io/bash)


